blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Copybook Generator Official Website
    url: https://wangchujiang.com/copybook-generator/
    about: Introduction to the Copybook Generator app on the official website!